<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <parent>
        <groupId>org.wso2</groupId>
        <artifactId>wso2</artifactId>
        <version>1.4</version>
    </parent>

    <groupId>org.wso2.identity.ssf</groupId>
    <modelVersion>4.0.0</modelVersion>
    <version>1.0.0-SNAPSHOT</version>
    <artifactId>identity-shared-signal-framework</artifactId>

    <packaging>pom</packaging>
    <name>Shared Signals Framework Support for WSO2 Identity Server</name>
    <description>SSF/CAEP stream management, discovery, and event delivery for WSO2 Identity Server</description>
    <url>http://wso2.org</url>

    <modules>
        <module>components/org.wso2.identity.event.ssf.publisher</module>
    </modules>

</project>
