/*
 * Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.wso2.identity.ssf.stream.management.api.service;

import org.wso2.identity.ssf.stream.management.api.exception.SSFStreamManagementException;
import org.wso2.identity.ssf.stream.management.api.model.StreamConfiguration;
import org.wso2.identity.ssf.stream.management.api.model.StreamStatus;

import java.util.List;

/**
 * Service interface for managing SSF event streams, as defined by the Shared Signals Framework
 * Stream Configuration and Stream Status APIs. A stream is persisted internally as a webhook via
 * {@code org.wso2.carbon.identity.webhook.management.api.service.WebhookManagementService} - this
 * service translates between the SSF spec's external shape and that internal model.
 */
public interface SSFStreamManagementService {

    /**
     * Create a new stream. {@code streamId} and {@code aud} on the given configuration are
     * ignored if present - {@code streamId} is generated by this service, and {@code aud} is
     * set from {@code receiverAudience} instead, since both are Transmitter-Supplied per spec.
     *
     * @param streamRequest    Receiver-supplied stream configuration (delivery, eventsRequested,
     *                         description).
     * @param receiverAudience The {@code aud} claim of the receiver's validated access token -
     *                         identifies the receiver, defaults to its OAuth2 client ID unless
     *                         a custom audience was configured for the application.
     * @param tenantDomain     Tenant domain.
     * @return The created stream configuration, including the generated streamId and aud.
     * @throws SSFStreamManagementException If an error occurs while creating the stream.
     */
    StreamConfiguration createStream(StreamConfiguration streamRequest, List<String> receiverAudience,
                                     String tenantDomain) throws SSFStreamManagementException;

    /**
     * Get a single stream's configuration by its stream ID.
     *
     * @param streamId     Stream ID.
     * @param tenantDomain Tenant domain.
     * @return The stream configuration.
     * @throws SSFStreamManagementException If an error occurs while retrieving the stream,
     *                                      or if no stream exists with the given ID.
     */
    StreamConfiguration getStream(String streamId, String tenantDomain) throws SSFStreamManagementException;

    /**
     * Get all stream configurations for a tenant.
     *
     * @param tenantDomain Tenant domain.
     * @return List of stream configurations.
     * @throws SSFStreamManagementException If an error occurs while retrieving the streams.
     */
    List<StreamConfiguration> getStreams(String tenantDomain) throws SSFStreamManagementException;

    /**
     * Partially update a stream configuration. Only Receiver-Supplied fields present on
     * {@code streamUpdate} are changed; fields left unset are kept as-is.
     *
     * @param streamUpdate Partial stream configuration, must include {@code streamId}.
     * @param tenantDomain Tenant domain.
     * @return The updated stream configuration.
     * @throws SSFStreamManagementException If an error occurs while updating the stream.
     */
    StreamConfiguration updateStream(StreamConfiguration streamUpdate, String tenantDomain)
            throws SSFStreamManagementException;

    /**
     * Fully replace a stream configuration's Receiver-Supplied fields.
     *
     * @param streamReplacement Full stream configuration, must include {@code streamId}.
     * @param tenantDomain      Tenant domain.
     * @return The replaced stream configuration.
     * @throws SSFStreamManagementException If an error occurs while replacing the stream.
     */
    StreamConfiguration replaceStream(StreamConfiguration streamReplacement, String tenantDomain)
            throws SSFStreamManagementException;

    /**
     * Delete a stream.
     *
     * @param streamId     Stream ID.
     * @param tenantDomain Tenant domain.
     * @throws SSFStreamManagementException If an error occurs while deleting the stream.
     */
    void deleteStream(String streamId, String tenantDomain) throws SSFStreamManagementException;

    /**
     * Get a stream's status.
     *
     * @param streamId     Stream ID.
     * @param tenantDomain Tenant domain.
     * @return The stream's status.
     * @throws SSFStreamManagementException If an error occurs while retrieving the status.
     */
    StreamStatus getStatus(String streamId, String tenantDomain) throws SSFStreamManagementException;

    /**
     * Update a stream's status. Only "enabled" and "disabled" are supported; "paused" is a
     * valid value per spec but is rejected, since it only has meaning for poll-based delivery.
     *
     * @param statusUpdate Status update, must include {@code streamId} and {@code status}.
     * @param tenantDomain Tenant domain.
     * @return The updated status.
     * @throws SSFStreamManagementException If an error occurs while updating the status, or if
     *                                      {@code status} is an unsupported value.
     */
    StreamStatus updateStatus(StreamStatus statusUpdate, String tenantDomain) throws SSFStreamManagementException;
}
